### PR TITLE
move s3client creation outside imageflow server code

### PR DESCRIPTION
**Pull request by edmacdonald**

### CODE REVIEW

**Comment by lilith** [comment]
I like this. I think we'll have to compensate for the changes and indirection with more documentation but it's certainly doable.

**Comment by edmacdonald** [comment]
@lilith is there anything else you would like to see in this?

**Comment by lilith** [comment]
I will probably roll this into a later breaking release that includes other
changes. Thank you so much for your work on this!

**Comment by edmacdonald** [comment]
@lilith any chance you would consider publishing a beta or alpha of the `Imageflow.Server.Storage.S3` package with these changes?  I've been using this in production without issue since opening this PR.

**Pull request merged**
