### PR TITLE
add support for following redirects in RemoteReader

### PR DESCRIPTION
**Pull request by edmacdonald**

### CODE REVIEW

**Comment by edmacdonald** [comment]
Hi @lilith , I looked at the build failure and it seems to be a test that unrelated to the code in the PR.  Please let me know if there is anything I can do to resolve.

**Comment by lilith** [comment]
Thank you so much! I'm not sure why CI is unhappy but I don't think it has anything to do with this PR. This will go out in the next release, hopefully within a few days. I'm still finishing up an in-progress feature.

**Comment by lilith** [comment]
Released

**Comment by edmacdonald** [comment]
Thanks for getting that out so quickly.  I saw it this morning and already have it deployed :^)

**Pull request merged**
