### PR TITLE
Remote Reader Blob Provider

### PR DESCRIPTION
**Pull request by edmacdonald**
Hi @lilith ,

I whipped up a remote reader implementation for your consideration.

I had intended to implement as a drop-in replacement server for clients using ImageResizer Remote Reader, but it sends `urlb64` and `hmac` on the query string, and `IBlobProvider.Fetch()` is only passed the path so I decided to implement with `urlb64` and `hmac` as part of the file name.

I also included a small change in the `HomeController` of the example project as it was applying the resizing query string parameters in the controller and the view.

### CODE REVIEW

**Comment by lilith** [comment]
Thank you so much! I will look at this in depth when I am back at my office
tomorrow, but it looks great so far.

**Comment by lilith** [comment]
Thank you so much! This is fantastic!

**Comment by lilith** [comment]
One note - this will cause all images to be converted to jpegs by default, because it appends .jpg when signing the URLs. It should inherit the file extension (PathHelpers.SanitizeImageExtension can help here) of the URL being signed.

**Comment by lilith** [comment]
I've fixed this (partially) in main. Note that remote URLs without image extensions will always be converted to jpeg format.

**Comment by edmacdonald** [comment]
Thanks @lilith !

**Pull request merged**
