### PR TITLE
Add error handling

### PR DESCRIPTION
**Pull request by edmacdonald**
This will address some of the mysterious errors as reported here:
https://github.com/imazen/imageflow-dotnet-server/issues/31#issue-744393915

For remotes that return 404's the RemoteReader was happily passing on the html page.

### CODE REVIEW

**Comment by lilith** [comment]
If I understand properly, calling GetClient() just once rather than on-demand can prevent DNS updates from propagating. 

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-5.0#consumption-patterns

It also looks like cookies could end up being shared across multiple requests unless that is blocked in configuration.

**Comment by lilith** [comment]
I think we need to spend a bit more time looking at the implementation details and try to get everything right in one breaking change rather than in multiple.

**Comment by lilith** [comment]
Have you looked into using Polly?

**Comment by edmacdonald** [comment]
What I really wanted to do was introduce the error handling, I should have resisted the urge to change the http client.  I've backed that stuff out, and will spend more time looking into that.  

I looked briefly at Polly, but didn't want to introduce a third-party dependency.  If you're OK with that, I'll look into that as well.

**Comment by lilith** [comment]
You're definitely headed in the right direction with using the factory
instead but you're right we need to make that a separate PR for the
breakage.

I am ok with adding dependencies to make it mor robust.

**Pull request merged**
